### ISSUE TITLE
GPU version don't work.

### ISSUE THREAD

**Issue by automataIA** [OpenDroneMap/NodeODM#231]
Enviroment:
OS: windos, ubuntu 22.04 wsl
DE: VsCode wsl 
language: python

## What is the problem?
I see, by running nvidia commands, that the gpu is seen by the nodeodm docker, but when I start a process it only uses the cpu.
## What should be the expected behavior?
it should perform the calculations using the available gpu

##  How can we reproduce this?
docker compose:

```yaml
services:
  nodeodm:
    image: opendronemap/nodeodm:gpu
    ports:
      - "8080:3000"
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_SECURE=False
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
```

pyodm>=1.5.12
